# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6938d3c66ca57365ca3e9488d2ed8fe977f6ff0e6139cceb5a3be04bca4e63e5bafd6ca55c28fd37dab9d6e0d63119f3034ec26750860d6845abd4057c7f26df

test:
  secret_key_base: cebebe437225e58167063ee2622f61f8f7735674a53691025411e6f3d0bc7c050676569f76e58de9ea14e9a98b4289c2f10f67f6bd8dcc3dc8f7b14009418b9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
